---
- name: Setup LXD Developer container
  hosts: all
  pre_tasks:
    - name: Update apt
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/mpd.yaml
    - include: tasks/nvim-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/java.yml
    - include: tasks/awesomewm.yml
    - include: tasks/brave.yml
    - include: tasks/google-chrome.yml
