- name: Git install
  apt:
    name: git
    state: present

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "inigomaringarcia@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Inigo Marin"
  tags:
  - git-personal
