- name: Install ZSH
  apt: name=zsh
  tags:
    - install
    - zsh

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  tags:
    - install
    - zsh

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  tags:
    - install
    - zsh

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - install
    - zsh

- name: Cloning  zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions.git
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - install
    - zsh
  
- name: Cloning  zsh-syntax-highlighting
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - install
    - zsh

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: not stat_rc_result.stat.exists
  tags:
    - install
    - zsh

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh
